/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-07-27 15:59:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newapplicant_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "bootstrap.jsp", out, false);
      out.write("\n");
      out.write("<title>HDZ - Create account</title>\n");
      out.write("<script>\n");
      out.write("\tfunction validateForm() {\n");
      out.write("\t\tvar x = document.forms[\"applicant\"][\"firstname\"].value;\n");
      out.write("\t\tvar text;\n");
      out.write("\t\tif (x == null || x == \"\") {\n");
      out.write("\t\t\ttext = \"Name must be filled out\";\n");
      out.write("\t\t\tdocument.getElementById(\"invalid\").innerHTML = text;\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tx = document.forms[\"applicant\"][\"email\"].value;\n");
      out.write("\t\tif (x == null || x == \"\") {\n");
      out.write("\t\t\ttext = (\"Email must be filled out\");\n");
      out.write("\t\t\tdocument.getElementById(\"invalid\").innerHTML = text;\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tx = document.forms[\"applicant\"][\"password\"].value;\n");
      out.write("\t\tif (x == null || x == \"\") {\n");
      out.write("\t\t\ttext = (\"Password must be filled out\");\n");
      out.write("\t\t\tdocument.getElementById(\"invalid\").innerHTML = text;\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tx = document.forms[\"applicant\"][\"dob\"].value;\n");
      out.write("\t\tif (x == null || x == \"\") {\n");
      out.write("\t\t\ttext = (\"Birthdate must be filled out\");\n");
      out.write("\t\t\tdocument.getElementById(\"invalid\").innerHTML = text;\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tx = document.forms[\"applicant\"][\"edu1\"].value;\n");
      out.write("\t\tif (x == null || x == \"\") {\n");
      out.write("\t\t\ttext = (\"You must specify one degree\");\n");
      out.write("\t\t\tdocument.getElementById(\"invalid\").innerHTML = text;\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tx = document.forms[\"applicant\"][\"job1\"].value;\n");
      out.write("\t\tif (x == null || x == \"\") {\n");
      out.write("\t\t\ttext = (\"You must specify one job\");\n");
      out.write("\t\t\tdocument.getElementById(\"invalid\").innerHTML = text;\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-sm-1\"></div>\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\n");
      out.write("\t\t\t\t<form action=\"NewApplicant\" onsubmit=\"return validateForm()\"\n");
      out.write("\t\t\t\t\tname=\"applicant\">\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-primary\">\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t<div align=\"left\">Personal</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t\tFirst name: <input type=\"text\" name=\"firstname\" id=\"firstname\" />\n");
      out.write("\t\t\t\t\t\t\t\tLast name: <input type=\"text\" name=\"lastname\" id=\"lastname\" /><br />\n");
      out.write("\t\t\t\t\t\t\t\tEmail: <input type=\"text\" name=\"email\" id=\"email\" /> Password:\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"password\" /><br />\n");
      out.write("\t\t\t\t\t\t\t\tDate of Birth: <input type=\"text\" name=\"dob\" id=\"dob\" />\n");
      out.write("\t\t\t\t\t\t\t\tVeteran Status: <select name=\"veteran\"><br />\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"yes\">Veteran</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"no\">Non-veteran</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select> <br /> Citizenship <select name=\"citizen\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"yes\">Citizen</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"no\">Non-citizen</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-primary\">\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t<div align=\"left\">Education</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t\tInstitution: <input type=\"text\" name=\"edu1\" id=\"edu1\" />\n");
      out.write("\t\t\t\t\t\t\t\tDegree: <input type=\"text\" name=\"degree1\" id=\"degree1\" /><br />\n");
      out.write("\t\t\t\t\t\t\t\tDate completed: <input type=\"text\" name=\"date1\" id=\"date1\" /> <br />\n");
      out.write("\t\t\t\t\t\t\t\t<br /> Institution: <input type=\"text\" name=\"edu2\" id=\"edu2\" />\n");
      out.write("\t\t\t\t\t\t\t\tDegree: <input type=\"text\" name=\"degree2\" id=\"degree2\" /><br />\n");
      out.write("\t\t\t\t\t\t\t\tDate completed: <input type=\"text\" name=\"date2\" id=\"date2\" /> <br />\n");
      out.write("\t\t\t\t\t\t\t\t<br /> Institution: <input type=\"text\" name=\"edu3\" id=\"edu3\" />\n");
      out.write("\t\t\t\t\t\t\t\tDegree: <input type=\"text\" name=\"degree3\" id=\"degree3\" /><br />\n");
      out.write("\t\t\t\t\t\t\t\tDate completed: <input type=\"text\" name=\"date3\" id=\"date3\" />\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<br />\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-primary\">\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t<div align=\"left\">Job History</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t\tJob title: <input type=\"text\" name=\"job1\" id=\"job1\" /> Company:\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"company1\" id=\"company1\" /><br /> Job\n");
      out.write("\t\t\t\t\t\t\t\tDescription: <input type=\"text\" name=\"jobdesc1\" id=\"jobdesc1\" />\n");
      out.write("\t\t\t\t\t\t\t\t<br /> Start date: <input type=\"text\" name=\"start1\" id=\"start1\" />\n");
      out.write("\t\t\t\t\t\t\t\tEnd date: <input type=\"text\" name=\"leave1\" id=\"leave1\" /> <br />\n");
      out.write("\t\t\t\t\t\t\t\t<br /> Job title: <input type=\"text\" name=\"job2\" id=\"job2\" />\n");
      out.write("\t\t\t\t\t\t\t\tCompany: <input type=\"text\" name=\"company2\" id=\"company2\" /><br />\n");
      out.write("\t\t\t\t\t\t\t\tJob Description: <input type=\"text\" name=\"jobdesc2\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"jobdesc2\" /> <br /> Start date: <input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"start2\" id=\"start2\" /> End date: <input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"leave2\" id=\"leave2\" /> <br /> <br /> Job title: <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"job3\" id=\"job3\" /> Company: <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"company3\" id=\"company3\" /><br /> Job\n");
      out.write("\t\t\t\t\t\t\t\tDescription: <input type=\"text\" name=\"jobdesc3\" id=\"jobdesc3\" />\n");
      out.write("\t\t\t\t\t\t\t\t<br /> Start date: <input type=\"text\" name=\"start3\" id=\"start3\" />\n");
      out.write("\t\t\t\t\t\t\t\tEnd date: <input type=\"text\" name=\"leave3\" id=\"leave3\" /> <br />\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-primary\">\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t<div align=\"left\">References</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t\tName: <input type=\"text\" name=\"refname1\" id=\"refname1\" />\n");
      out.write("\t\t\t\t\t\t\t\tPhone: <input type=\"text\" name=\"refphone1\" id=\"refphone1\" /><br />\n");
      out.write("\t\t\t\t\t\t\t\tEmail: <input type=\"text\" name=\"refemail1\" id=\"refemail1\" />\n");
      out.write("\t\t\t\t\t\t\t\tPosition: <input type=\"text\" name=\"refpos1\" id=\"refpos1\" /><br />\n");
      out.write("\t\t\t\t\t\t\t\t<br /> Name: <input type=\"text\" name=\"refname2\" id=\"refname2\" />\n");
      out.write("\t\t\t\t\t\t\t\tPhone: <input type=\"text\" name=\"refphone2\" id=\"refphone2\" /><br />\n");
      out.write("\t\t\t\t\t\t\t\tEmail: <input type=\"text\" name=\"refemail2\" id=\"refemail2\" />\n");
      out.write("\t\t\t\t\t\t\t\tPosition: <input type=\"text\" name=\"refpos2\" id=\"refpos2\" /><br />\n");
      out.write("\t\t\t\t\t\t\t\t<br /> Name: <input type=\"text\" name=\"refname3\" id=\"refname3\" />\n");
      out.write("\t\t\t\t\t\t\t\tPhone: <input type=\"text\" name=\"refphone3\" id=\"refphone3\" /><br />\n");
      out.write("\t\t\t\t\t\t\t\tEmail: <input type=\"text\" name=\"refemail3\" id=\"refemail3\" />\n");
      out.write("\t\t\t\t\t\t\t\tPosition: <input type=\"text\" name=\"refpos3\" id=\"refpos3\" /><br />\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<p id=\"invalid\"></p>\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"submit\" id=\"submit\" value=\"Submit\" />\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-sm-1\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
