/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-07-05 20:13:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CrabyWebPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h1>Crabcake Recipe </h1>\n");
      out.write("<h2>Ingredients: </h2>\n");
      out.write("<ul>\n");
      out.write("1 lb. jumbo lump or backfin crab meat\n");
      out.write("2 slices bread or bread crumbs\n");
      out.write("1 tbsp. mayonnaise (light or regular)\n");
      out.write("1 tbsp. Dijon mustard\n");
      out.write("2 tsp. Old Bay seasoning\n");
      out.write("1 tbsp. snipped parsley \n");
      out.write("1 egg (or substitute for special diets)\n");
      out.write("tartar sauce or cocktail sauce\n");
      out.write("</ul>\n");
      out.write("<h1>Directions</h1>\n");
      out.write("<p>\n");
      out.write("Beat the egg in a bowl. Trim the crusts from the bread and break the slices into small pieces. Add these pieces to the egg. Mix in the mayonnaise, Dijon mustard, Chesapeake seasoning and parsley, and beat well.\n");
      out.write("\n");
      out.write("Place the crabmeat in a bowl and pour the egg mixture over the top. Gently toss or fold the ingredients together, taking care not to break up the lumps of crabmeat.\n");
      out.write("\n");
      out.write("Form the cakes by hand into patties about 3 inches around and 3/4-inch thick. Shape should be like a cookie, not like a meatball or golf ball. Place the cakes in the refrigerator for at least 45 minutes before cooking. This is very important so the cakes don't fall apart.\n");
      out.write("<p>\n");
      out.write("<h1>Broil the Crab Cakes:</h1>\n");
      out.write("<p>\n");
      out.write("Slip them under a preheated broiler until nicely browned, turning to cook evenly, about 4 to 5 minutes on each side.\n");
      out.write("<p>\n");
      out.write("\n");
      out.write("<h1>Or saute:</h1>\n");
      out.write("<p>\n");
      out.write("Heat a small amount of butter or olive oil in a skillet and saute the cakes, turning several times, until golden brown or about 8 minutes total cooking time.\n");
      out.write("\n");
      out.write("Serve at once with tartar sauce, mustard, or cocktail sauce on the side.\n");
      out.write("Serves 6 people\n");
      out.write("<p>\n");
      out.write("\n");
      out.write("<img src=\"https://upload.wikimedia.org/wikipedia/commons/1/1d/Crabcakes_and_salad,_Tate_Modern.jpg\" alt=\"Crabcake\">\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
